name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 30 2 * * */21

jobs:
  R-test:
    name: R
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        R: [ 'oldrel', 'release', 'devel' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2.8.3
        with:
          r-version: ${{ matrix.R }}

      - name: Install R dependency testthat
        run: |
          install.packages('testthat', type="source", force=T)
        shell: Rscript {0}

      - name: Install R dependency remotes
        run: |
          install.packages('remotes')
        shell: Rscript {0}

      - name: Install R package dependencies
        run: |
          remotes::install_deps(pkgdir='./R/', dependencies=T)
        shell: Rscript {0}

      - name: Build
        run: make test_R

  R-test-ubsan:
    name: R with sanitizers (${{ matrix.compiler }})
    runs-on: ubuntu-latest
    container: wch1/r-debug
    strategy:
      fail-fast: false
      matrix:
        include:
          - sanitizer: san
            compiler: gcc
          - sanitizer: csan
            compiler: clang
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        shell: bash
        run: |
          cd R
          RDscript${{ matrix.sanitizer }} -e "install.packages(c('testthat'))"
          RD${{ matrix.sanitizer }} CMD build .
          RD${{ matrix.sanitizer }} CMD INSTALL SyncRNG_*.tar.gz || exit -1

      - name: Run tests with sanitizer
        shell: bash
        run: |
          cd R/tests
          exit_code=0
          RDscript${{ matrix.sanitizer }} testthat.R >> tests.log 2>&1 || exit_code=-1
          cat ./tests.log
          (! grep -q 'undefined-behavior' tests.log)
          exit_code=$?
          exit ${exit_code}

  python-test:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        py: [ '3.8', '3.11' ] # minimal and latest
    steps:
      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make test_python_direct

